### ISSUE TITLE
Issues not showing in Gitlab

### ISSUE THREAD

**Issue by sebastianzillessen** [mmozuras/pronto#145]
Hi,

I'm trying this gem out right now because I would like to integrate it in my project at work. We use gitlab 8.5.5. My config file looks like this:

```
#export GITLAB_API_HTTPARTY_OPTIONS="{verify: false}"
all:
  exclude:
    - 'spec/**/*'
gitlab:
  api_private_token: <token>
  api_endpoint: http://<url>.com/api/v3/
max_warnings: 150
verbose: true
```

If I run it locally I get:

````
pronto run -c origin/develop
Running Pronto::JSHint
Running Pronto::Rubocop
lib/tasks/populate.rake:228 I: Prefer single-quoted strings when you don't need string interpolation or special symbols.
lib/tasks/populate.rake:228 I: Surrounding space missing for operator `+`.
lib/tasks/populate.rake:228 I: Line is too long. [148/80]
lib/tasks/populate.rake:228 I: Prefer single-quoted strings when you don't need string interpolation or special symbols.
lib/tasks/populate.rake:228 I: Prefer single-quoted strings when you don't need string interpolation or special symbols.
lib/tasks/populate.rake:231 I: Surrounding space missing for operator `+`.
````
If I run it to the remote I get:
````
pronto run -f gitlab -c origin/develop
Running Pronto::JSHint
Running Pronto::Rubocop
Creating commit comment on c36d9008155c8c3e168fce51e8c219ff6729c6a9
Creating commit comment on c36d9008155c8c3e168fce51e8c219ff6729c6a9
Creating commit comment on c36d9008155c8c3e168fce51e8c219ff6729c6a9
Creating commit comment on c36d9008155c8c3e168fce51e8c219ff6729c6a9
4 Pronto messages posted to GitLab
````

Unfortunately the commit comments don't show up on the server. Is there anyway how I could debug this?

Thanks!
