### ISSUE TITLE
No comments on bitbucket pull request

### ISSUE THREAD

**Issue by TLmaK0** [mmozuras/pronto#164]
I have created a pull requests in bitbucket and then launch

 `bundle exec pronto run -f bitbucket_pr -c origin/master`

Pronto shows rubocop errors but nothing about comments in bitbucket. Any change to bitbucket section in .pronto.yml doesn't show any error.

If I launch it with github_pr formater then I get a "Octokit::InvalidRepository" which is correct.

this is my .pronto.yml

```
bitbucket:
  username: user
  password: pass
max_warnings: 150
verbose: true
```

I'm using pronto 0.6.0
