### ISSUE TITLE
Add support for two formatters

### ISSUE THREAD

**Issue by dankohn** [mmozuras/pronto#83]
On our continuous integration server, I would like to be able to run:
```bash
bundle exec pronto run -f=text,github -c origin/master --exit-code
```
so that I can both get errors posted into Github and to show up in the CI logs. However, `formatter` currently takes a string instead of an array: https://github.com/mmozuras/pronto/blob/master/lib/pronto/cli.rb#L39

**Comment by dankohn** [comment]
In case others have the same desire, here is some bash cleverness for a workaround making use of parallelism, using YML syntax for CircleCI:
```yml
test:
  post:
    - case $CIRCLE_NODE_INDEX in 0) bundle exec pronto run -f text -c origin/master --exit-code ;; 1) bundle exec pronto run -f github -c origin/master ;; esac:
        parallel: true
```
